title: Мапперский кодекс
description: Сборник разрешений и инструкций для маппинга шаттлов и их проверки для StarHorizon Frontier.
header_links:
  - title: Главная
    url: /
  - title: Цена шаттлов
    url: ./markdown/shuttle-costs.html