title: Мапперский кодекс
description: Сборник разрешений и инструкций для маппинга шаттлов и их проверки для StarHorizon Frontier.
header_links:
  - title: Главная
    url: https://lastronautl.github.io/StarHorizon-Mapping/
  - title: Типы и тиры
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/types-and-tiers.html
  - title: Правила маппинга
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/rules-for-mapping.html
  - title: Cоздание прототипов
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/prototype-creation.html
  - title: Приёмная верфь
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/reception-shipyard.html
  - title: Цена шаттлов
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/shuttle-costs.html
  - title: Команды
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/commands.html
  - title: Ошибки
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/fix-error.html
  - title: Рендер
    url: https://lastronautl.github.io/StarHorizon-Mapping/markdown/create-render.html